export { default as Header } from './Header/Header';
export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as Faq } from './Faq/Faq';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';
export { default as Error404 } from './Error404/Error404';
export { default as DateTime } from './shared/DateTime/DateTime';
export { default as SocialMedia } from './shared/SocialMedia/SocialMedia';
